### ISSUE TITLE
实现 cocos 常用的几个 wrapper

### ISSUE THREAD

**Issue by jareguo** [fireball-x/runtime-cocos2d-js#1]
目前的 engine-framework 不依赖于特定引擎，cocos runtime 需要通过 engine-framework 的注册 api 来嵌入 fireball。
API 的定义入口在 engine-framework/src/runtime/index.js，runtime 需要访问的接口都在 Fire.Runtime 名空间下。请参考 engine-framework 的目录结构来组织代码。
- Fire.Runtime.NodeWrapper  
    所有 wrapper 的基类，继承这个类来实现 cocos 的指定逻辑，例如 CCSpriteFrameWrapper
- Fire.Runtime.SceneWrapper  
    场景的基类，继承自 NodeWrapper。继承这个类来实现 cocos 的场景管理，例如 CCSceneWrapper
- Fire.Runtime.registerNodeType  
    注册你继承出来的 wrapper，例如 `Fire.Runtime.registerNodeType(cc.Node, CCNodeWrapper);`
- <del>Fire.Runtime.registerMixin</del>  
    (mixin 引擎有提供预设操作，这个接口 runtime 暂时用不到)

之后 wrapper 还会增加序列化相关的 api，接口也会增加一些 runtime 的 init 等操作，到时会在另外建立 issue 说明。
如果对接口有不同意见，欢迎提出。

**Comment by jareguo** [comment]
具体需要实现哪些 wrapper，请根据 cocos 的实际情况自由选择，前期以验证功能为主，不需要把每个类都封装一遍，只要挑选常用的几个就行。

**Comment by jareguo** [comment]
我把 build 的 task 提交了，你可以试试 gulp build 能不能把脚本都 build 到 bin 目录下。这个 build 出来的脚本是给手机版加载的。src 下的源文件是给编辑器加载的。

**Comment by 2youyouo2** [comment]
ok
