### ISSUE TITLE
默认没有 playing 的情况下 cocos2d 会劫持键盘事件

### ISSUE THREAD

**Issue by jwu** [fireball-x/runtime-cocos2d-js#19]
@2youyouo2 @jareguo 在没有 playing 状态下, cocos2d 不应该劫持键盘事件, 目前如果到达 scene 里的时候, 键盘事件会组织所有 main menu 的快捷键.

**Comment by jareguo** [comment]
@2youyouo2 请参考 fireball-x/dev#659，当时我是发现在 CCInputExtension 里有一些拦截输入的代码，所以把整个类都去掉了。不过现在显然这个类是不能去掉的，必须做成 initRuntime 时不激活，在 playRuntime 时才激活，请找找看有什么方法。
