### ISSUE TITLE
Bitmap Font 的疑问

### ISSUE THREAD

**Issue by jwu** [fireball-x/runtime-cocos2d-js#26]
在 canvas-assets 中我发现 bitmap font 的数据处理方式从原先的解析 .fnt 导入到 library 变成现在的 .fnt 保留, 我想知道, 在 runtime 中我们是 cocos2d-js 负责读取 .fnt 么? 还是我们在 runtime 中还要进行 2 次解析? 如果是后者, 那么应该在 meta 过程中完成解析导入的操作.

**Comment by jwu** [comment]
@jareguo @2youyouo2

**Comment by 2youyouo2** [comment]
cocos2d-js 会负责读取 .fnt
