### ISSUE TITLE
NodeWrapper 的 Inspector 结构

### ISSUE THREAD

**Issue by jwu** [fireball-x/runtime-cocos2d-js#35]
Hi @jareguo @2youyouo2 , 我需要知道我们目前的 Node Wrapper 以及他们在 Inspector 中的结构, 这样我好归纳属性, 以便抽出可以共享的部分. 你们可以这样书写:

**Runtime.NodeWrapper:**

   - Transform
    - Position
    - Rotation
    - Scale
   - Visual
    - Color
    - Size

**Comment by 2youyouo2** [comment]
**Runtime.ButtonWrapper:**

   - Texture
    - Normal
    - Pressed
    - Disabled
   - Label
    - Text
    - Font (字体文件)
    - FontFamily (字体名)
    - FontSize

**Comment by 2youyouo2** [comment]
**Runtime.SpriteWrapper:**

   - Texture
    - Texture

**Comment by 2youyouo2** [comment]
**Runtime.BitmapFontWrapper:**

   - Label
    - Text
    - Font
    - Anchor
    - Align

**Comment by 2youyouo2** [comment]
**Runtime.ParticleWrapper:**

   - Default
    - File
    - Custom (如果没勾上Custom，则其他项目都隐藏，否则显示)

   - Custom
    - particleCount
    - maxParticles
    - duration
    - emissionRate
    - life
    - lifeVariance
    - startColor
    - startColorVariance
    - endColor
    - endColorVariance
    - angle
    - angleVariance
    - startSize
    - startSizeVariance
    - endSize
    - endSizeVariance
    - startSpin
    - startSpinVariance
    - endSpin
    - endSpinVariance
    - sourcePosition
    - sourcePositionVariance
    - positionType
    - emitterMode ( 如果为Runtime.ParticleEmitMode.Gravity则显示Gravity项目, 否则显示Radius)

   - Gravity
    - gravity
    - speed
    - speedVariance
    - tangentialAccel
    - tangentialAccelVariance
    - radialAccel
    - radialAccelVariance
    - rotationIsDir

   - Radius
    - startRadius
    - startRadiusVariance
    - endRadius
    - endRadiusVariance
    - rotatePerSecond
    - rotatePerSecondVariance
