### ISSUE TITLE
请将 convertPointsToLocal, convertPointsToWorld 改名为 transformPointsToLocal, transformPointsToWorld

### ISSUE THREAD

**Issue by jwu** [fireball-x/runtime-cocos2d-js#49]
RT

另外, 请加入 transformPointToLocal, transformPointToWorld, 并且他们会返回结果.

**Comment by jareguo** [comment]
我觉得接口最好别太冗余，如果一定要有 transformPointToLocal 的话，就把 transformPointsToLocal 都去掉吧。
