### ISSUE TITLE
定义 Asset 类型

### ISSUE THREAD

**Issue by jareguo** [fireball-x/runtime-cocos2d-js#9]
Asset 类的需求来自 https://github.com/fireball-x/fireball/issues/35 ，实现在 engine-framework/src/core/asset/asset.js，可通过 Fire.Asset 访问到。
请实现现有 node wrapper 对应的 asset 类型，需要实现的接口有 Asset.validateAsset 和 asset.createNode。
这两个接口都会在编辑器下调用，可以在方法**内部** require node js 模块。

**Comment by jareguo** [comment]
等 asset-db 接口完成后，定义好的类型还需要进行注册，这里先不用注册。

**Comment by jareguo** [comment]
之前 fireball-x/fireball#35 等 issue 的定义里没有 **特化的meta** 这个概念，现在新加入了 meta 的定义规则所以工作有些改动。一方面是 validateAsset 要转移到 meta 身上，另一方面主要是要把通用资源类型放到 canvas-assets 这个 repo 里。

大致做法请参考 fireball-x/fireball#42，具体问题和PR请提交给 jwu。

**Comment by jwu** [comment]
我这里补充说一下, validateAsset 这个方法并不是一个必要选项, 应该说大部分情况都是可以不用定义 validate 的. 我这里只有这个例子是用了 validate: https://github.com/fireball-x/asset-db/blob/master/test/meta.js#L11

这么说吧, 除非你需要通过读取文件内容 或者 通过路径名的特殊形式来判断一个 asset 时, 才需要启用 validate. 正常情况下, 我们通过: `assetdb.register ( extname, folder, meta )` 已经可以覆盖大部分 asset:

```javascript
assetdb.register( '.png', false, Editor.metas.texture );
assetdb.register( '.jpg', false, Editor.metas.texture );
assetdb.register( '.sprite', false, Editor.metas.sprite );
assetdb.register( '.atlas', true, Editor.metas.atlas );
```

需要注意的是, 同一个 meta 可以反复注册给不同后缀, 另外就是, 我没有提供"后缀数组" 的参数形式, 必须一个一个注册.
